<?php
/**
 * See LICENSE.txt for license details.
 */
?>
<form action="" id="co-comment-form">
    <ul class="form-list">
        <li class="wide">
            <label for="comment"><?php echo $this->__('Additional Comment') ?></label>
            <div class="input-box">
                <textarea id="comment" name="comment"><?php echo $this->htmlEscape($this->getComment()) ?></textarea>
            </div>
       </li>
    </ul>
</form>
<div class="buttons-set" id="comment-buttons-container">
    <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button type="button" class="button" title="<?php echo $this->__('Continue') ?>" onclick="comment.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    <span id="comment-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>
